version: '3.3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: maxpokrovsky/foodgram_backend
    env_file: .env
    depends_on:
      - db
    restart: on-failure
    volumes:
      - static_volume:/backend_static
      - media_volume:/app/media
      - ../data:/app/data
  frontend:
    image: maxpokrovsky/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static_volume:/static
  nginx:
    image: nginx:1.19.3
    depends_on:
      - backend
      - frontend
    ports:
      - 8000:80
    volumes:
      - static_volume:/usr/share/nginx/html/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../docs/:/usr/share/nginx/html/api/docs/
