# Generated by Django 3.2.3 on 2024-01-20 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20240120_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(auto_now_add=True, verbose_name='Архивировано')),
                ('ingredient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archive_data', to='recipes.ingredient', verbose_name='Ингредиент')),
            ],
            options={
                'verbose_name': 'архивированный ингредиент',
                'verbose_name_plural': 'Архивированные ингредиенты',
                'ordering': ('ingredient__name',),
            },
        ),
    ]
