# Generated by Django 3.2.3 on 2024-01-25 13:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_archivedingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='Неправильный формат HEX.', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Цвет'),
        ),
    ]
