# Generated by Django 3.2.3 on 2024-01-26 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20240126_1424'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeIngredient',
            new_name='IngredientInRecipe',
        ),
        migrations.RenameModel(
            old_name='RecipeTag',
            new_name='TagInRecipe',
        ),
    ]
