# Generated by Django 3.2.3 on 2024-02-01 10:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20240129_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(message='Неправильный формат поля slug. ^[-a-zA-Z0-9_]+$', regex='^[-a-zA-Z0-9_]+$')], verbose_name='Слаг'),
        ),
    ]
