# Generated by Django 3.2.3 on 2024-01-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
        ('users', '0002_auto_20240118_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodgramuser',
            options={'ordering': ('email',), 'verbose_name': 'пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='foodgramuser',
            name='favorite_recipes',
            field=models.ManyToManyField(related_name='favorited_by', to='recipes.Recipe', verbose_name='Избранные рецепты'),
        ),
        migrations.AddField(
            model_name='foodgramuser',
            name='shopping_list',
            field=models.ManyToManyField(related_name='added_to_shopping_list_by', to='recipes.Recipe', verbose_name='Список покупок'),
        ),
    ]
