# Generated by Django 3.2.3 on 2024-01-26 15:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20240126_1522'),
        ('users', '0003_auto_20240119_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodgramuser',
            name='favorite_recipes',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='recipes.Recipe', verbose_name='Избранные рецепты'),
        ),
        migrations.AlterField(
            model_name='foodgramuser',
            name='shopping_list',
            field=models.ManyToManyField(blank=True, related_name='added_to_shopping_list_by', to='recipes.Recipe', verbose_name='Список покупок'),
        ),
        migrations.AlterField(
            model_name='foodgramuser',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to=settings.AUTH_USER_MODEL, verbose_name='Подписки'),
        ),
    ]
